#pragma once

#define preference_API_enabled "ApiEna"
#define preference_API_Token "ApiToken"
#define preference_config_Auth "ConfAuth"
#define preference_device_id_lock "deviceId"
#define preference_restart_on_disconnect "restdisc"
#define preference_callback_key_prefix "cbUrl"

#define preference_rssi_update_interval "rssiup"
#define preference_restart_ble_beacon_lost "rstbcn"
#define preference_query_interval_lockstate "lockStInterval"
#define preference_query_interval_configuration "configInterval"
#define preference_query_interval_battery "batInterval"
#define preference_query_interval_keypad "kpInterval"
#define preference_keypad_control_enabled "kpEnabled"
#define preference_command_nr_of_retries "nrRetry"
#define preference_command_retry_delay "rtryDelay"
#define preference_lock_max_keypad_code_count "maxkpad"
#define preference_access_level "accLvl"