#pragma once

//#define DEBUG
#define NUKI_REST_BRIDGE_VERSION "0.90"
#define NUKI_REST_BRIDGE_BUILD "unknown"
#define NUKI_REST_BRIDGE_DATE "13.03.25"
#define NUKI_REST_BRIDGE_HW "OLIMEX ESP32-POE-ISO"

#define NUKI_TASK_SIZE 8192
#define NETWORK_TASK_SIZE 8192
#define WEBCFGSERVER_TASK_SIZE 8192

#define WEBCFGSERVER_PORT 80
#define REST_SERVER_PORT 8080
#define CHAR_BUFFER_SIZE 4096

#define MAX_AUTHLOG 5
#define MAX_KEYPAD 10