#pragma once

#define NUKI_REST_BRIDGE_VERSION "1.9.0"
#define NUKI_REST_BRIDGE_BUILD "main"
#define NUKI_REST_BRIDGE_DATE "2026-06-02"
#define NUKI_REST_BRIDGE_HW "OLIMEX ESP32-POE-ISO"

#define NUKI_TASK_SIZE 8192
#define NETWORK_TASK_SIZE 6144
#define WEBCFGSERVER_TASK_SIZE 6144
#define LOGGER_QUEUE_TASK_SIZE 3072

#define LOG_MSG_MAX_LEN 256
#define LOG_QUEUE_MAX_ENTRYS 10

#define WEBCFGSERVER_PORT 80
#define REST_SERVER_PORT 8080
#define CHAR_BUFFER_SIZE 4096
#define CHAR_BUFFER_HTTP_TIMEOUT pdMS_TO_TICKS(5000)
#define REST_ARGS_BUFFER_SIZE 768

#define MAX_AUTHLOG 5
#define MAX_KEYPAD 10
#define MAX_TIMECONTROL 10
#define MAX_AUTH 10

#define PREFERENCE_NAME "nukibridge"
#define DEVICE_NAME "NukiBridge"