#pragma once

// Token suffix definitions for HAR configuration
#define TOKEN_SUFFIX_STAT "STAT"
#define TOKEN_SUFFIX_REMACCSTAT "REMACCSTAT"
#define TOKEN_SUFFIX_UPTM "UPTM"
#define TOKEN_SUFFIX_RSTFW "RSTFW"
#define TOKEN_SUFFIX_RSTESP "RSTESP"
#define TOKEN_SUFFIX_NBVER "NBVER"
#define TOKEN_SUFFIX_NBBUILD "NBBUILD"
#define TOKEN_SUFFIX_FREEHP "FREEHP"

#define TOKEN_SUFFIX_WFRSSI "WFRSSI"

#define TOKEN_SUFFIX_BLEADDR "BLEADDR"
#define TOKEN_SUFFIX_BLESTR "BLESTR"
#define TOKEN_SUFFIX_BLERSSI "BLERSSI"

#define TOKEN_SUFFIX_LCKSTAT "LCKSTAT"
#define TOKEN_SUFFIX_LCKNGOSTAT "LCKNGOSTAT"
#define TOKEN_SUFFIX_LCKTRIG "LCKTRIG"
#define TOKEN_SUFFIX_LCKNMOD "LCKNMOD"
#define TOKEN_SUFFIX_LCKCMPLSTAT "LCKCMPLSTAT"

#define TOKEN_SUFFIX_DOORSTAT "DOORSTAT"
#define TOKEN_SUFFIX_DOORSCRIT "DOORSCRIT"

#define TOKEN_SUFFIX_KPCRIT "KPCRIT"

#define TOKEN_SUFFIX_LCKBATCRIT "LCKBATCRIT"
#define TOKEN_SUFFIX_LCKBATLVL "LCKBATLVL"
#define TOKEN_SUFFIX_LCKBATCHRG "LCKBATCHRG"
#define TOKEN_SUFFIX_BATVOLT "BATVOLT"
#define TOKEN_SUFFIX_BATDRAIN "BATDRAIN"
#define TOKEN_SUFFIX_BATMAXTURNCUR "BATMAXTURNCUR"
#define TOKEN_SUFFIX_BATLCKDIST "BATLCKDIST"

#define HAR_CAT_GENERAL "general"
#define HAR_CAT_KEY_TURN_STATE "keystate"
#define HAR_CAT_BATTERY_REPORT "battery"
